spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.146.130:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  rabbitmq:
    host: 192.168.146.158
    password: guest
    username: guest
    port: 5672
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true
env:
  test4-2
girl:
  name: lili-1-2
  age: 18
